# This file was generated by GoReleaser. DO NOT EDIT.
cask "ago" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_darwin_x86_64.tar.gz"
      sha256 "1bbb52a00da5f7968213af075641ba57e97145db0e92785ed024f1697f665963"
    end
    on_arm do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_darwin_arm64.tar.gz"
      sha256 "5b7afb6c61285a0c76351669c653b844ebbb9cbfe56d5b87beddb6f20d92a5b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_linux_x86_64.tar.gz"
      sha256 "b2fbd1158c41510be456e8f2b8dbdd6d93450f9e2dde922c63807c59841466d2"
    end
    on_arm do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_linux_arm64.tar.gz"
      sha256 "46fcfbabfc94795cc3f697cafbb057b6c8e5dc2812dc126718ad2e41c53945b6"
    end
  end

  name "ago"
  desc "Linter that enforces one way to write Go"
  homepage "https://github.com/agentstation/ago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ago"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ago"], sudo: false
    end
  end

  # No zap stanza required

end
