# This file was generated by GoReleaser. DO NOT EDIT.
cask "ago" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_darwin_x86_64.tar.gz"
      sha256 "210c4a46ca03269eeea4692ada808d1d697563e2b6c62747782c25c1d1f5353b"
    end
    on_arm do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_darwin_arm64.tar.gz"
      sha256 "94c87b4ba00a81e50a5e98bfd6c689f9e7ecf24a0660810cb81e85d7086c48a6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_linux_x86_64.tar.gz"
      sha256 "4e3694058c4f8317a9b8f0fea81dbf4ebfb316f6bf7a997495b4261eb7f8cfa4"
    end
    on_arm do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_linux_arm64.tar.gz"
      sha256 "609b3c655fe3f199f70680cdd6d9a7551fc27df3b8841da5400a8896ba738c76"
    end
  end

  name "ago"
  desc "A restriction-only linter for Go"
  homepage "https://github.com/agentstation/ago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ago"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ago"], sudo: false
    end
  end

  # No zap stanza required

end
