# This file was generated by GoReleaser. DO NOT EDIT.
cask "ago" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_darwin_x86_64.tar.gz"
      sha256 "755678ec258f7a7c56f2687ef4da2939b7bfd3a0bb752343c59dd2828f68ef11"
    end
    on_arm do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_darwin_arm64.tar.gz"
      sha256 "2987e8074257ed4e80a231782ff470461a397ab63228bdb5a151c113b512ad95"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_linux_x86_64.tar.gz"
      sha256 "e97fccc33a16785d90952ba91cd9e4e39317bb6d34a625524349dd5653d81d5f"
    end
    on_arm do
      url "https://github.com/agentstation/ago/releases/download/v#{version}/ago_#{version}_linux_arm64.tar.gz"
      sha256 "ddc9461c1f77ec314ce674e86857a9a76f6934074c3796641b01da18562bda8e"
    end
  end

  name "ago"
  desc "A restriction-only linter for Go"
  homepage "https://github.com/agentstation/ago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ago"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ago"], sudo: false
    end
  end

  # No zap stanza required

end
