# This file was generated by GoReleaser. DO NOT EDIT.
cask "starmap" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "dca8bf1151623280e93cd8ef071fa95eedbc03cedcf6e8d3858c49355276f388"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5ab0a3404759907543932718ebb9035cf600dd5014ee9cf01caf7f90442b5067"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "75ba290b05cd7d7f22b925ce9c36d29f6be03637fd55829395349185726673a6"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "017391ee1df514f4398d9428923794ef0e78021fb4c4acde41830f0a3980d0a1"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "starmap"
  desc "AI Model Catalog System - Discover, compare, and sync AI models across providers"
  homepage "https://github.com/agentstation/starmap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starmap"
  bash_completion "completions/starmap.bash"
  fish_completion "completions/starmap.fish"
  zsh_completion "completions/starmap.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starmap"], sudo: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Starmap has been installed! ⭐🗺️

    Quick start:
      starmap models list              # List all AI models
      starmap providers fetch openai   # Fetch live model data
      starmap update                   # Update entire catalog
      starmap --help                   # Show all commands

    Shell completions have been installed to:
      Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d
      Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions
      Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d

    Documentation: https://starmap.agentstation.ai/
  EOS
end
