# This file was generated by GoReleaser. DO NOT EDIT.
cask "starport" do
  on_macos do
    depends_on arch: :arm64
  end
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/starport"], sudo: false
    end
  end

  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "3b6dd19bb7e9e88de84ac6c795128f06e96cfb7eaf50f62f784c6f1a849d96ca"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f3e13682bf38f32317449f9d3a1195fb48e82e4f0cf960a006968d4b84d2323"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6eb508d8342ca80cc895c3a4513c13ff5b815691d6c429d517627c1699b79afe"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_linux_arm64.tar.gz"
    end
  end

  name "starport"
  desc "OpenAI- and OpenRouter-compatible LLM inference gateway"
  homepage "https://github.com/agentstation/starport"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starport"
  manpage "manpages/starport.1"
  bash_completion "completions/starport.bash"
  fish_completion "completions/starport.fish"
  zsh_completion "completions/starport.zsh"

  # No zap stanza required

end
