# This file was generated by GoReleaser. DO NOT EDIT.
cask "starmap" do
  version "0.16.5"

  on_macos do
    on_intel do
      sha256 "1305eb0c9b5404f0bd0a2538ac5e03782fa5bc22b0715d7472d20228b8a4cfe0"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "30efdb503b3c4fe4d1e059a9a5a5a591643887a0cbde0fa2114d7547107f4ee2"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa30977cde657ddbf3920a95a242d4697424b3cfbdb955361d515d5a719d3be8"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "53c971d232ce0494cdad7f386b1780ac4ba28a744e0ff6453814f5c40193c495"
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "starmap"
  desc "AI Model Catalog System - Discover, compare, and sync AI models across providers"
  homepage "https://github.com/agentstation/starmap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starmap"
  bash_completion "completions/starmap.bash"
  fish_completion "completions/starmap.fish"
  zsh_completion "completions/starmap.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starmap"], sudo: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Starmap has been installed! ⭐🗺️

    Quick start:
      starmap models list              # List all AI models
      starmap providers fetch openai   # Fetch live model data
      starmap update                   # Update entire catalog
      starmap --help                   # Show all commands

    Shell completions have been installed to:
      Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d
      Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions
      Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d

    Documentation: https://starmap.agentstation.ai/
  EOS
end
