# This file was generated by GoReleaser. DO NOT EDIT.
cask "starport" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "6d8a7582d14d24c46dfc1609f4137228be44bd8fbdf7d71d9a9cd7baa7b046a4"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e1f31ee3922115c47dbf43c4f244a3e7b7c55862f7f23fed687cb49ab29584dc"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2a98b4098404db3ea2bbc9cf89090c0baa06b93d9e94991ddd78c5d2b26c67e"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c25fa629f3189e9198637d5143551050cf448ba954d37a2db1c83de72b0a008a"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_linux_arm64.tar.gz"
    end
  end

  name "starport"
  desc "OpenAI- and OpenRouter-compatible LLM inference gateway"
  homepage "https://github.com/agentstation/starport"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starport"
  manpage "manpages/starport.1"
  bash_completion "completions/starport.bash"
  fish_completion "completions/starport.fish"
  zsh_completion "completions/starport.zsh"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starport"], sudo: false
    end
  end

  # No zap stanza required

end
