# This file was generated by GoReleaser. DO NOT EDIT.
cask "starport" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "707a405c4bfc7447c1656bd8c1cd80e75fbfe4a61d3a7b805031ddc547e8abd4"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a2a58428ec88438ba48039871cd98cde8585f361540eb659b9c9e99fa12f8fd3"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6392a0d3b763171ddd44f56dbc504688252daf15aa6e1b295662884c9a7442a"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1efbda81b60c1ba556d0e370a9bfaf4ac63693692b8814df73e2d3558b3e2a94"
      url "https://github.com/agentstation/starport/releases/download/v#{version}/starport_#{version}_linux_arm64.tar.gz"
    end
  end

  name "starport"
  desc "OpenAI- and OpenRouter-compatible LLM inference gateway"
  homepage "https://github.com/agentstation/starport"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starport"
  manpage "manpages/starport.1"
  bash_completion "completions/starport.bash"
  fish_completion "completions/starport.fish"
  zsh_completion "completions/starport.zsh"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starport"], sudo: false
    end
  end

  # No zap stanza required

end
