# This file was generated by GoReleaser. DO NOT EDIT.
cask "starmap" do
  name "starmap"
  desc "AI Model Catalog System - Discover, compare, and sync AI models across providers"
  homepage "https://github.com/agentstation/starmap"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "starmap"
  bash_completion "completions/starmap.bash"
  zsh_completion "completions/starmap.zsh"
  fish_completion "completions/starmap.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_darwin_x86_64.tar.gz"
      sha256 "7e01e8328b58a26b0e7ab12e988a55b2e4906dc0d59392dad3bca242a3f8effc"
    end
    on_arm do
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_darwin_arm64.tar.gz"
      sha256 "103c106f606391b5fab6093078494d6c0962477e40a40e21f65fc1c5d0546381"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_linux_x86_64.tar.gz"
      sha256 "4917490b87c1cf7867459e5b803a814e0725c22a89d186960ade1331028c5e00"
    end
    on_arm do
      url "https://github.com/agentstation/starmap/releases/download/v#{version}/starmap_#{version}_linux_arm64.tar.gz"
      sha256 "803757ca4a6df5dfeaf2cb05cba3d84ec3c7dbcade21c5c67d74abedc411bb16"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/starmap"], sudo: false
    end
  end

  caveats do
    "Starmap has been installed! ⭐🗺️"
    ""
    "Quick start:"
    "  starmap list models              # List all AI models"
    "  starmap fetch models --provider openai  # Fetch live model data"
    "  starmap update                   # Update entire catalog"
    "  starmap --help                   # Show all commands"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://starmap.agentstation.ai/"
  end

  # No zap stanza required
end
