# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenizer" do
  desc "High-performance tokenizer implementations in Go with unified CLI"
  homepage "https://github.com/agentstation/tokenizer"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenizer"
  bash_completion "completions/tokenizer.bash"
  zsh_completion "completions/tokenizer.zsh"
  fish_completion "completions/tokenizer.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.6/tokenizer_0.0.6_darwin_x86_64.tar.gz"
      sha256 "655bb99493ac1a24904194e6d74a7ebd9cc4e2652894dbb3ca3d3920b297d9c7"
    end
    on_arm do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.6/tokenizer_0.0.6_darwin_arm64.tar.gz"
      sha256 "eae191bf3b2a0b2294a2e7c82c04368691aa5a672b59b9c4f2889732f395f0a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.6/tokenizer_0.0.6_linux_x86_64.tar.gz"
      sha256 "13d7261c242783d2d6585338667353cea932cad88e4f42e6c01815a27a4ae4ef"
    end
    on_arm do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.6/tokenizer_0.0.6_linux_arm64.tar.gz"
      sha256 "02694a751dcd70a13586e30e7a330f5bd9f4e0d234739dff32f167d9a5486ddc"
    end
  end

  conflicts_with formula: [
      "tokenizer",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenizer"], sudo: false
    end
  end

  caveats do
    "Tokenizer has been installed! 🚀"
    ""
    "Quick start:"
    "  tokenizer llama3 encode "Hello, world!"     # Encode text to tokens"
    "  tokenizer llama3 decode 128000 9906 128001  # Decode tokens to text"
    "  tokenizer llama3 info                       # Show tokenizer info"
    "  tokenizer --help                            # Show all commands"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://github.com/agentstation/tokenizer"
  end

  # No zap stanza required
end
