# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenizer" do
  desc "High-performance tokenizer implementations in Go with unified CLI"
  homepage "https://github.com/agentstation/tokenizer"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenizer"
  bash_completion "completions/tokenizer.bash"
  zsh_completion "completions/tokenizer.zsh"
  fish_completion "completions/tokenizer.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.7/tokenizer_0.0.7_darwin_x86_64.tar.gz"
      sha256 "1e285ff789ac3c6613ae5699a9c972ab9a75bbb139b4ab528ed914b4b76fc182"
    end
    on_arm do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.7/tokenizer_0.0.7_darwin_arm64.tar.gz"
      sha256 "1adb332a1ae8997ee4bbe49fabd56dfa32e46ab9b5ab21fd7552f35857127d25"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.7/tokenizer_0.0.7_linux_x86_64.tar.gz"
      sha256 "6878830f8d1dee64d18eaa5595c14aa97338155a90e052bc3364d7c09b7de13d"
    end
    on_arm do
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.7/tokenizer_0.0.7_linux_arm64.tar.gz"
      sha256 "4b9ef055e38f2499b044ae0a4aae3fdbf425a680075520bc6ee4b90c1580d30a"
    end
  end

  conflicts_with formula: [
      "tokenizer",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenizer"], sudo: false
    end
  end

  caveats do
    "Tokenizer has been installed! 🚀"
    ""
    "Quick start:"
    "  tokenizer llama3 encode 'Hello, world!'     # Encode text to tokens"
    "  tokenizer llama3 decode 128000 9906 128001  # Decode tokens to text"
    "  tokenizer llama3 info                       # Show tokenizer info"
    "  tokenizer --help                            # Show all commands"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://github.com/agentstation/tokenizer"
  end

  # No zap stanza required
end
