# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenizer" do
  name "tokenizer"
  desc "High-performance tokenizer implementations in Go with unified CLI"
  homepage "https://github.com/agentstation/tokenizer"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenizer"
  bash_completion "completions/tokenizer.bash"
  zsh_completion "completions/tokenizer.zsh"
  fish_completion "completions/tokenizer.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentstation/tokenizer/releases/download/v#{version}/tokenizer_#{version}_darwin_x86_64.tar.gz"
      sha256 "86ae838a8ed6d3c9bc9ef0ff433504d7afe747cf198e50d083d84a1c5a765696"
    end
    on_arm do
      url "https://github.com/agentstation/tokenizer/releases/download/v#{version}/tokenizer_#{version}_darwin_arm64.tar.gz"
      sha256 "7da583461172e431e1c4e3ee9d7472d220050578e61f16bb587fb82fab16018d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/tokenizer/releases/download/v#{version}/tokenizer_#{version}_linux_x86_64.tar.gz"
      sha256 "46200e1f0d23870376e3cfb4ffb194e2ab611a553c5a1657fb7800c9081da185"
    end
    on_arm do
      url "https://github.com/agentstation/tokenizer/releases/download/v#{version}/tokenizer_#{version}_linux_arm64.tar.gz"
      sha256 "d39e2c4edcf39480bcc1fd27184f01755e9aa19442b140a2a80ab85c46cc0c60"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokenizer"], sudo: false
    end
  end

  caveats do
    "Tokenizer has been installed! 🚀"
    ""
    "Quick start:"
    "  tokenizer llama3 encode 'Hello, world!'     # Encode text to tokens"
    "  tokenizer llama3 decode 128000 9906 128001  # Decode tokens to text"
    "  tokenizer llama3 info                       # Show tokenizer info"
    "  tokenizer --help                            # Show all commands"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://github.com/agentstation/tokenizer"
  end

  # No zap stanza required
end
