# This file was generated by GoReleaser. DO NOT EDIT.
cask "vhs" do
  desc "A tool for recording terminal GIFs and SVGs"
  homepage "https://github.com/agentstation/vhs"
  version "0.10.0-as.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vhs"
  bash_completion "completions/vhs.bash"
  zsh_completion "completions/vhs.zsh"
  fish_completion "completions/vhs.fish"
  depends_on formula: [
      "ffmpeg",
      "ttyd",
    ]

  on_macos do
    on_intel do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.3/vhs_0.10.0-as.3_darwin_x86_64.tar.gz"
      sha256 "b5a3008fbf1d6b12a06b67320c4d5b08429c6637bec1f1f81f6440206b461b61"
    end
    on_arm do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.3/vhs_0.10.0-as.3_darwin_arm64.tar.gz"
      sha256 "8db229e4641aa477fb36840c9c1aecf7b41bb01a992e07758711d98df93f8b0c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.3/vhs_0.10.0-as.3_linux_x86_64.tar.gz"
      sha256 "79ae6685fce71ea4c47a8185213dc34b915290b2c43d3aa15584df2b3f0805a8"
    end
    on_arm do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.3/vhs_0.10.0-as.3_linux_arm64.tar.gz"
      sha256 "9c6ace4b0fefef1d73eda4320ba985214d454bdd72d49fef8ad0d90715321ebd"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vhs"], sudo: false
    end
  end

  caveats do
    "VHS has been installed! 🎬"
    ""
    "Quick start:"
    "  vhs new demo.tape           # Create a new tape file"
    "  vhs demo.tape              # Generate output (GIF/MP4/WebM/SVG)"
    "  vhs record > session.tape   # Record terminal session"
    "  vhs --help                 # Show all commands"
    ""
    "SVG Output (Fork Feature):"
    "  Output demo.svg            # Generate animated SVG"
    "  vhs demo.tape --no-svg-opt # Disable SVG optimization"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://github.com/agentstation/vhs"
  end

  # No zap stanza required
end
