# This file was generated by GoReleaser. DO NOT EDIT.
cask "vhs" do
  desc "A tool for recording terminal GIFs and SVGs"
  homepage "https://github.com/agentstation/vhs"
  version "0.10.0-as.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vhs"
  bash_completion "completions/vhs.bash"
  zsh_completion "completions/vhs.zsh"
  fish_completion "completions/vhs.fish"
  depends_on formula: [
      "ffmpeg",
      "ttyd",
    ]

  on_macos do
    on_intel do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.2/vhs_0.10.0-as.2_darwin_x86_64.tar.gz"
      sha256 "2f396ae2f2c6c660ec4914a9c98556b2b72a405e0442e0589bf2941e9233ff44"
    end
    on_arm do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.2/vhs_0.10.0-as.2_darwin_arm64.tar.gz"
      sha256 "c5d63dd3b6e258a463476cce7ec1871432a3634d28040e6e4ac60448ff66284d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.2/vhs_0.10.0-as.2_linux_x86_64.tar.gz"
      sha256 "0f364ecd522f09ec9fb27c7496d5a0de8de93e7dbfa813c5cb0d971f4dddb10e"
    end
    on_arm do
      url "https://github.com/agentstation/vhs/releases/download/v0.10.0-as.2/vhs_0.10.0-as.2_linux_arm64.tar.gz"
      sha256 "b373c8e975fb684126058ea4ad2fb5bcc04e10b7b23b8aea84b122d91e26e1df"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vhs"], sudo: false
    end
  end

  caveats do
    "VHS has been installed! 🎬"
    ""
    "Quick start:"
    "  vhs new demo.tape           # Create a new tape file"
    "  vhs demo.tape              # Generate output (GIF/MP4/WebM/SVG)"
    "  vhs record > session.tape   # Record terminal session"
    "  vhs --help                 # Show all commands"
    ""
    "SVG Output (Fork Feature):"
    "  Output demo.svg            # Generate animated SVG"
    "  vhs demo.tape --no-svg-opt # Disable SVG optimization"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://github.com/agentstation/vhs"
  end

  # No zap stanza required
end
