# This file was generated by GoReleaser. DO NOT EDIT.
cask "vhs" do
  name "vhs"
  desc "A tool for recording terminal GIFs and SVGs"
  homepage "https://github.com/agentstation/vhs"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vhs"
  bash_completion "completions/vhs.bash"
  zsh_completion "completions/vhs.zsh"
  fish_completion "completions/vhs.fish"
  depends_on formula: [
      "ffmpeg",
      "ttyd",
    ]

  on_macos do
    on_intel do
      url "https://github.com/agentstation/vhs/releases/download/v#{version}/vhs_#{version}_darwin_x86_64.tar.gz"
      sha256 "590c63133e12b7865cd3062aa9e7ba611698ca4a0853cb9c7b1537de89b5727a"
    end
    on_arm do
      url "https://github.com/agentstation/vhs/releases/download/v#{version}/vhs_#{version}_darwin_arm64.tar.gz"
      sha256 "01fe5478bf5ad21ccc0ac7a1e705b8c310de3bceb607781484a7daf9d892a531"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentstation/vhs/releases/download/v#{version}/vhs_#{version}_linux_x86_64.tar.gz"
      sha256 "1775c3b357abf09fbd47db593aecc638e20080fd8ad8e8ba2fd925df56e7a262"
    end
    on_arm do
      url "https://github.com/agentstation/vhs/releases/download/v#{version}/vhs_#{version}_linux_arm64.tar.gz"
      sha256 "668517f8ac7b9e04172f64f44cb92bcde66c0a81502c0a24fe8e755229c9dc23"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vhs"], sudo: false
    end
  end

  caveats do
    "VHS has been installed! 🎬"
    ""
    "Quick start:"
    "  vhs new demo.tape           # Create a new tape file"
    "  vhs demo.tape              # Generate output (GIF/MP4/WebM/SVG)"
    "  vhs record > session.tape   # Record terminal session"
    "  vhs --help                 # Show all commands"
    ""
    "SVG Output (Fork Feature):"
    "  Output demo.svg            # Generate animated SVG"
    "  vhs demo.tape --no-svg-opt # Disable SVG optimization"
    ""
    "Shell completions have been installed to:"
    "  Bash: #{HOMEBREW_PREFIX}/etc/bash_completion.d"
    "  Zsh:  #{HOMEBREW_PREFIX}/share/zsh/site-functions"
    "  Fish: #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"
    ""
    "Documentation: https://github.com/agentstation/vhs"
  end

  # No zap stanza required
end
