# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenizer < Formula
  desc "High-performance tokenizer implementations in Go with unified CLI"
  homepage "https://github.com/agentstation/tokenizer"
  version "0.0.2"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.2/tokenizer_0.0.2_darwin_x86_64.tar.gz"
      sha256 "0b43dc693c1dc2bd75a0e07dd8c75ad04a2882fa3d231868d8808034c8493845"

      def install
        if build.bottle?
          bin.install "tokenizer"
        else
          # Build from source with version information
          ldflags = %W[
            -s -w
            -X main.version=#{version}
            -X main.commit=#{Utils.git_short_head}
            -X main.buildDate=#{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
            -X main.goVersion=#{Formula["go"].version}
          ]
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/tokenizer"
        end

        # Install documentation
        doc.install "README.md", "LICENSE", "CLAUDE.md"
        doc.install "llama3/README.md" => "llama3-README.md"
        doc.install "llama3/IMPLEMENTATION.md" => "llama3-IMPLEMENTATION.md"

        # Install examples if they exist
        if Dir.exist?("examples")
          pkgshare.install "examples"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.2/tokenizer_0.0.2_darwin_arm64.tar.gz"
      sha256 "22e9229c57975aa484eeca48328d8cd36c08e6ea0479573c81802fc5445ab484"

      def install
        if build.bottle?
          bin.install "tokenizer"
        else
          # Build from source with version information
          ldflags = %W[
            -s -w
            -X main.version=#{version}
            -X main.commit=#{Utils.git_short_head}
            -X main.buildDate=#{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
            -X main.goVersion=#{Formula["go"].version}
          ]
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/tokenizer"
        end

        # Install documentation
        doc.install "README.md", "LICENSE", "CLAUDE.md"
        doc.install "llama3/README.md" => "llama3-README.md"
        doc.install "llama3/IMPLEMENTATION.md" => "llama3-IMPLEMENTATION.md"

        # Install examples if they exist
        if Dir.exist?("examples")
          pkgshare.install "examples"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.2/tokenizer_0.0.2_linux_x86_64.tar.gz"
      sha256 "9824dfb55fd8067fa97fc3855748a8dcd3a6e3579d3891bbefbb09330e7e88dc"
      def install
        if build.bottle?
          bin.install "tokenizer"
        else
          # Build from source with version information
          ldflags = %W[
            -s -w
            -X main.version=#{version}
            -X main.commit=#{Utils.git_short_head}
            -X main.buildDate=#{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
            -X main.goVersion=#{Formula["go"].version}
          ]
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/tokenizer"
        end

        # Install documentation
        doc.install "README.md", "LICENSE", "CLAUDE.md"
        doc.install "llama3/README.md" => "llama3-README.md"
        doc.install "llama3/IMPLEMENTATION.md" => "llama3-IMPLEMENTATION.md"

        # Install examples if they exist
        if Dir.exist?("examples")
          pkgshare.install "examples"
        end
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.2/tokenizer_0.0.2_linux_armv6.tar.gz"
      sha256 "7a40a0b8fdb3be654b6cc1e34c304be3dce1d6b5e46ac7aaab0df04b5d8e87e7"
      def install
        if build.bottle?
          bin.install "tokenizer"
        else
          # Build from source with version information
          ldflags = %W[
            -s -w
            -X main.version=#{version}
            -X main.commit=#{Utils.git_short_head}
            -X main.buildDate=#{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
            -X main.goVersion=#{Formula["go"].version}
          ]
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/tokenizer"
        end

        # Install documentation
        doc.install "README.md", "LICENSE", "CLAUDE.md"
        doc.install "llama3/README.md" => "llama3-README.md"
        doc.install "llama3/IMPLEMENTATION.md" => "llama3-IMPLEMENTATION.md"

        # Install examples if they exist
        if Dir.exist?("examples")
          pkgshare.install "examples"
        end
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/agentstation/tokenizer/releases/download/v0.0.2/tokenizer_0.0.2_linux_arm64.tar.gz"
      sha256 "c204b4165772cede4e3c211d42e061ffedc9a698155e58fa1b5024abb98bd9fb"
      def install
        if build.bottle?
          bin.install "tokenizer"
        else
          # Build from source with version information
          ldflags = %W[
            -s -w
            -X main.version=#{version}
            -X main.commit=#{Utils.git_short_head}
            -X main.buildDate=#{Time.now.utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
            -X main.goVersion=#{Formula["go"].version}
          ]
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/tokenizer"
        end

        # Install documentation
        doc.install "README.md", "LICENSE", "CLAUDE.md"
        doc.install "llama3/README.md" => "llama3-README.md"
        doc.install "llama3/IMPLEMENTATION.md" => "llama3-IMPLEMENTATION.md"

        # Install examples if they exist
        if Dir.exist?("examples")
          pkgshare.install "examples"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Tokenizer has been installed! 🚀

      Quick start:
        tokenizer llama3 encode "Hello, world!"     # Encode text to tokens
        tokenizer llama3 decode 128000 9906 128001  # Decode tokens to text
        tokenizer llama3 info                       # Show tokenizer info
        tokenizer --help                            # Show all commands

      Documentation: https://github.com/agentstation/tokenizer
    EOS
  end

  test do
    # Test version command
    output = shell_output("#{bin}/tokenizer version")
    assert_match version.to_s, output
    assert_match "commit:", output
    assert_match "built:", output
    assert_match "go version:", output

    # Test help output
    assert_match "Usage:", shell_output("#{bin}/tokenizer --help")
    assert_match "Available Commands:", shell_output("#{bin}/tokenizer --help")

    # Test llama3 subcommand
    assert_match "llama3", shell_output("#{bin}/tokenizer --help")
    assert_match "encode", shell_output("#{bin}/tokenizer llama3 --help")

    # Test encoding
    output = shell_output("#{bin}/tokenizer llama3 encode 'Hello, world!'")
    assert_match "128000", output # begin_of_text token
    assert_match "9906", output   # "Hello" token
    assert_match "128001", output # end_of_text token

    # Test decoding
    output = shell_output("#{bin}/tokenizer llama3 decode 128000 9906 11 1917 0 128001")
    assert_match "Hello", output
    assert_match "world", output

    # Test info command
    output = shell_output("#{bin}/tokenizer llama3 info")
    assert_match "Vocabulary Size: 128256", output
    assert_match "Regular Tokens: 128000", output
    assert_match "Special Tokens: 256", output

    # Test piping
    output = pipe_output("#{bin}/tokenizer llama3 encode", "Test input")
    assert_match "128000", output # begin_of_text token
  end
end
